const strings = {
	confirmTitle: 'Success!',
  confirmDescription: 'Thanks for connecting with us at CIT. Someone will be in contact with you in the next week to follow up',
  messageHeader: 'Latest Message',
  kidsHeader: 'citKids',
  youthHeader: 'CITYouth',
  christmasHeader: 'Christmas Market',
  eventsHeader: 'Announcements',
  eventsSorry: 'Sorry',
  eventsNoEvents: 'Looks like there are no upcoming announcements. Please check back later for more updates',
  connectHeader: 'Connect',
  connectTitle: 'Get connected with us',
  connectDescription: 'We know that it\'s important for you to find a church that really fits. We can connect you with one of our pastors to answer any questions you might have about our church\'s beliefs, community, and culture.',
  prayerHeader: "Prayer Requests",
  prayerTitle: "Prayer Request",
  prayerDescription: "Our prayer team would love to pray for you and your prayer request. We could pray for you annonymously, or if you would like for us to pray for you by name, please put in your contact information.",
  nextHeader: 'Next Steps',
  nextTitle: 'Take Your Next Step',
  nextDescription: 'Next Steps is a fun, one-time small group experience to help you get to know CIT better, ask questions, and get connected to church. Whether you\'re brand new or have been at CIT for years, Next Steps is a great way to go further in your faith and partner with the church to move our mission forward.',
  alphaHeader: 'Try Alpha',
  givingHeader: 'Giving',
  givingTitle: 'Give to our mission',
  givingDescription: 'Thank you for deciding to give to CIT. Your donation helps us fulfill our mission as a church, to lead people into a life changing relationship with Jesus.',
  groupsHeader: 'Community Groups',
  volunteerHome: 'Join A Team',
  volunteerHeader: 'Volunteer',
  volunteerTitle: 'Join A Team',
  volunteerDescription: 'Our teams are dedicated to bringing our very best to our God. We would love for you to become part of a team and discover all that God has purposed for your life.',
  loginHeader: 'Login',
	statsHeader: 'Stats',
  statsDescription: 'Below is a table of volunteers who missed 3 of their last 4 scheduled weeks.',
};

export default strings;
